### ISSUE TITLE
Can't watch live on apple home kit

### ISSUE THREAD

**Issue by minhquan313** [Brandawg93/homebridge-ezviz#16]
I am using C8C camera, Pi 4gb Ram but when opening apple homekit, I can't see online video. Please fix it, thanks.
<img width="1447" alt="Screen Shot 2021-07-01 at 12 52 03" src="https://user-images.githubusercontent.com/80441462/124073202-0a5b2280-da6c-11eb-900e-e6f8f9db8abd.png">

**Comment by mohamedkeven** [comment]
[EZVIZ] Error: Command failed with exit code 1: /usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/ -vframes 1 -f mjpeg -
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x3be2390] Connection to tcp://192.168.1.2:554?timeout=0 failed: No route to host
rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/: No route to host

    at makeError (/usr/local/lib/node_modules/homebridge-ezviz/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/homebridge-ezviz/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 {
  shortMessage: 'Command failed with exit code 1: /usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  command: '/usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  escapedCommand: '"/usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg" -i "rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/" -vframes 1 -f mjpeg -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 33 2e 31 20 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 32 30 30 30 2d 32 30 32 30 20 74 68 65 20 46 ... 1376 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
[20/12/2021, 05:39:31] [EZVIZ] Streaming started for C8C(G64947900)
[20/12/2021, 05:39:33] [EZVIZ] STREAM: rtsp://admin:GPBXAT@192.168.1.2/Streaming/Channels/1/: No route to host
[20/12/2021, 05:39:33] [EZVIZ] Streaming stopped for C8C(G64947900)
