### ISSUE TITLE
[EZVIZ] Error: Command failed with exit code 1

### ISSUE THREAD

**Issue by cuonocucco** [Brandawg93/homebridge-ezviz#25]
I have Homebridge installed on Raspberry 3B + and EZVIZ cameras. The plugin after installation and configuration worked without problems. Inside the Apple Home app the videos had a slow start, but they started playing. Since yesterday the message I attach appears in the log and the cameras show me the preview image, but the Live video does not load me. I am not an expert and I would like to understand where the problem is. Thank you
____________________________________________________________________________________________________________
In th Log file I've this message:
[EZVIZ] Error: Command failed with exit code 1: /usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:*****@***.***.***.**/Streaming/Channels/1/ -vframes 1 -f mjpeg -
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x3b83390] Connection to tcp://***.***.***.**:554?timeout=0 failed: No route to host
rtsp://admin:*****@***.***.***.**/Streaming/Channels/1/: No route to host

 at makeError (/usr/local/lib/node_modules/homebridge-ezviz/node_modules/execa/lib/error.js:60:11)
 at handlePromise (/usr/local/lib/node_modules/homebridge-ezviz/node_modules/execa/index.js:118:26)
 at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 1: /usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:*****@***.***.***.**/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  command: '/usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:*****@***.***.***.**/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  escapedCommand: '"/usr/local/lib/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg" -i "rtsp://admin:*****@***.***.***.**/Streaming/Channels/1/" -vframes 1 -f mjpeg -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 33 2e 31 20 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 32 30 30 30 2d 32 30 32 30 20 74 68 65 20 46 ... 1382 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
____________________________________________________________________________________________________________

**Comment by Brandawg93** [comment]
```
rtsp://admin:@...*/Streaming/Channels/1/: No route to host
```

It looks like Homebridge cannot connect to your camera.

**Comment by cuonocucco** [comment]
I checked the plugin settings: EZVIZ account and cameras setup and everything looks fine. The cameras are perfectly visible in the EZVIZ app.

**Comment by Brandawg93** [comment]
The EZVIZ app may be using the external endpoint to connect to the camera. The Homebridge app only uses the internal endpoint since the device running Homebridge should be on the same network as the camera.

**Comment by andreyxc** [comment]
Tell me you can get information about the movement from the camera? 
New cameras identifying people.
