### ISSUE TITLE
Can't make EZViz plugin work with HOOB 4

### ISSUE THREAD

**Issue by Packster01** [Brandawg93/homebridge-ezviz#27]
Greetings,

I used to have the EZVIZ plugin would perfectly under Hoob 3, but now I am having a tough time to get it working under HOOB 4.

I have un-installed / re-installed the pluging - double checked my username/password and cameras serial and confirm code 100 times.

This is what I get in the LOG:

9/6/2021, 5:07:13 PMHOOBSEZVIZERROR2 Factor Authentication accounts are not supported at this time.
9/6/2021, 5:07:13 PMHOOBSEZVIZERRORUnable to retrieve access token.

Any help or suggestions would help!

Thanks!
(I have overwritten the sensitive usernames/serial below with "XXXXX" )

{
    "platform": "EZVIZ",
    "region": "312",
    "email": "XXXXX",
    "password": "XXXX",
    "cameras": [
        {
            "serial": "XXXXXXX",
            "username": "admin",
            "code": "XXXXXX"
        },
        {
            "serial": "XXXXXX",
            "username": "admin",
            "code": "XXXXXX"
        },
        {
            "serial": "XXXXXX",
            "username": "admin",
            "code": "XXXXXX"
        },
        {
            "serial": "XXXXXX",
            "username": "admin",
            "code": "XXXXXX"
        },
        {
            "serial": "XXXXXX",
            "username": "admin",
            "code": "XXXXXX"
        }
    ]
}

**Comment by Brandawg93** [comment]
I would suggest contacting HOOBS support. You can either email them or @hoobs on the discord server provided in the readme.
