### ISSUE TITLE
 [EZVIZ] Unable to retrieve access token.

### ISSUE THREAD

**Issue by Maddah979** [Brandawg93/homebridge-ezviz#9]
hi,
 I gust install homebridge ezviz  and settings every thing put i get this error 

[5/7/2021, 5:18:06 AM] [EZVIZ] 2 Factor Authentication accounts are not supported at this time.
[5/7/2021, 5:18:06 AM] [EZVIZ] Unable to retrieve access token.

What did I do wrong?

**Comment by dieptang** [comment]
> > [5/7/2021, 5:18:06 AM] [EZVIZ] 2 Factor Authentication accounts are not supported at this time.

Hello, How to turn off 2 FA login ?

**Comment by Brandawg93** [comment]
@dieptang https://github.com/Brandawg93/homebridge-ezviz/issues/47
